"use client";

import { useState, useRef, useEffect, useCallback } from "react";

interface ExportReportProps {
  content: string;
  title?: string;
  severity?: string;
}

function formatAsMarkdown(content: string, title: string, severity?: string): string {
  const date = new Date().toISOString().replace("T", " ").split(".")[0] + " UTC";
  const lines: string[] = [];

  lines.push(`# Kubernetes Alert Analysis Report`);
  lines.push("");
  lines.push(`**Report Type:** ${title}`);
  lines.push(`**Generated:** ${date}`);
  if (severity) {
    lines.push(`**Severity:** ${severity}`);
  }
  lines.push(`**Tool:** K8s Alert Summarizer`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(content);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("*Generated by K8s Alert Summarizer*");

  return lines.join("\n");
}

function formatAsText(content: string, title: string, severity?: string): string {
  const date = new Date().toISOString().replace("T", " ").split(".")[0] + " UTC";
  const divider = "=".repeat(60);
  const lines: string[] = [];

  lines.push(divider);
  lines.push("  KUBERNETES ALERT ANALYSIS REPORT");
  lines.push(divider);
  lines.push("");
  lines.push(`Report Type:  ${title}`);
  lines.push(`Generated:    ${date}`);
  if (severity) {
    lines.push(`Severity:     ${severity}`);
  }
  lines.push(`Tool:         K8s Alert Summarizer`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("");
  // Strip markdown formatting for plain text
  const plainContent = content
    .replace(/#{1,6}\s/g, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1");
  lines.push(plainContent);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("Generated by K8s Alert Summarizer");
  lines.push(divider);

  return lines.join("\n");
}

function extractSeverity(content: string): string | undefined {
  const match = content.match(/(?:severity|priority)[:\s]*(P[0-4])/i);
  return match ? match[1] : undefined;
}

export default function ExportReport({ content, title = "AI Analysis", severity }: ExportReportProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  const detectedSeverity = severity || extractSeverity(content);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const copyMarkdown = useCallback(async () => {
    const md = formatAsMarkdown(content, title, detectedSeverity);
    try {
      await navigator.clipboard.writeText(md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* noop */ }
    setOpen(false);
  }, [content, title, detectedSeverity]);

  const downloadTxt = useCallback(() => {
    const text = formatAsText(content, title, detectedSeverity);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `k8s-report-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setOpen(false);
  }, [content, title, detectedSeverity]);

  const printPDF = useCallback(() => {
    // Set print metadata
    document.title = `K8s Alert Report - ${new Date().toISOString().slice(0, 10)}`;

    // Add a temporary print header
    const printHeader = document.createElement("div");
    printHeader.id = "print-report-header";
    printHeader.innerHTML = `
      <div style="text-align: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #e5e7eb;">
        <h1 style="font-size: 22px; font-weight: 700; color: #111; margin: 0 0 8px 0;">Kubernetes Alert Analysis Report</h1>
        <div style="display: flex; justify-content: center; gap: 24px; font-size: 13px; color: #555;">
          <span><strong>Type:</strong> ${title}</span>
          <span><strong>Date:</strong> ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
          ${detectedSeverity ? `<span><strong>Severity:</strong> <span style="padding: 2px 8px; border-radius: 4px; font-weight: 700; background: ${detectedSeverity === "P0" ? "#fecaca" : detectedSeverity === "P1" ? "#fed7aa" : "#fef3c7"}; color: ${detectedSeverity === "P0" ? "#991b1b" : detectedSeverity === "P1" ? "#9a3412" : "#92400e"};">${detectedSeverity}</span></span>` : ""}
        </div>
      </div>
    `;
    document.body.prepend(printHeader);

    // Add print footer
    const printFooter = document.createElement("div");
    printFooter.id = "print-report-footer";
    printFooter.innerHTML = `
      <div style="text-align: center; margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #999;">
        Generated by K8s Alert Summarizer
      </div>
    `;
    document.body.appendChild(printFooter);

    window.print();

    // Clean up
    document.getElementById("print-report-header")?.remove();
    document.getElementById("print-report-footer")?.remove();
    setOpen(false);
  }, [title, detectedSeverity]);

  if (!content) return null;

  const actions = [
    {
      label: copied ? "Copied!" : "Copy as Markdown",
      icon: copied
        ? "M5 13l4 4L19 7"
        : "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2",
      onClick: copyMarkdown,
    },
    {
      label: "Download .txt",
      icon: "M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z",
      onClick: downloadTxt,
    },
    {
      label: "Print as PDF",
      icon: "M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z",
      onClick: printPDF,
    },
  ];

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-400 hover:text-zinc-200 rounded-lg text-xs font-medium transition-colors"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Export
      </button>

      {open && (
        <div className="export-dropdown absolute right-0 top-full mt-2 w-52 py-1 rounded-xl border border-zinc-700/50 bg-zinc-900/90 dark:bg-zinc-900/90 backdrop-blur-xl shadow-2xl z-50 animate-fade-in">
          <div className="px-3 py-2 text-[10px] uppercase tracking-wider text-zinc-500 font-semibold border-b border-zinc-800">
            Export Report
          </div>
          {actions.map((action) => (
            <button
              key={action.label}
              onClick={action.onClick}
              className="w-full flex items-center gap-3 px-3 py-2.5 text-sm text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/50 transition-colors"
            >
              <svg className="w-4 h-4 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={action.icon} />
              </svg>
              <span>{action.label}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
